name: mishi
description: music app

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.24.0+24

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  internet_connection_checker: ^0.0.1+4
  equatable: ^2.0.3
  dio: ^4.0.6
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_svg: ^1.1.3
  get_it: ^7.2.0
  cached_network_image: ^3.2.1
  chewie: ^1.3.6
#  audioplayers: ^1.0.1
  path_provider: ^2.0.11
  http: ^0.13.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4
  flutter_sms: ^2.3.3
  dots_indicator: ^2.1.0
  flutter_swipe_detector: ^2.0.0
#  firebase_dynamic_links: ^4.3.6
  intl_phone_field: ^3.1.0
  package_info_plus: ^1.4.3+1
  url_launcher: ^6.1.5
#  magic_sdk: ^0.3.0
  walletconnect_dart: ^0.0.11
  firebase_messaging: ^14.2.1
#  dart_jsonwebtoken: ^2.4.2
  timer_count_down: ^2.2.1
  video_player: ^2.4.7
  google_sign_in: ^5.4.1
  flutter_local_notifications: ^11.0.1
  cloud_firestore: ^4.3.1
  shimmer: ^2.0.0
  just_audio: ^0.9.30
  wakelock: ^0.6.2
  webview_flutter: ^3.0.4
#  flutter_inapp_purchase: ^5.3.1
  in_app_purchase: ^3.0.8
  in_app_review: ^2.0.6
  device_info_plus: ^8.0.0
#  eartho_one: ^1.2.3
#  package_info: ^0.4.3+2
#  media_notification: ^0.0.5

#  awesome_notifications: ^0.6.21

  purchases_flutter: ^4.0.0
  in_app_update: ^4.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  flutter_launcher_icons: ^0.10.0
  cast: ^1.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true

  image_path: "assets/images/laucher.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/logo.png"
#    background_color: "#hexcode"
#    theme_color: "#hexcode"



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
